version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: ./web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: ./app.docker
        volumes:
            - ./laravel-app:/var/www
        links:
            - cache
        environment:
            - "DB_HOST=db"
            - "DB_PORT=5432"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
    db:
        image: postgres:9.6
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=secret"
            - "POSTGRES_DB=app"
        ports:
            - "54321:5432"
    cache:
        image: redis:3.0
        ports:
            - "63791:6379"
